name: Github Release
on:
  push:
    branches:
      - main
      - dev

jobs:
  build-android:
    name: Create Android build
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - uses: actions/checkout@v3
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/checkout@v3
      - name: Install Android dependencies
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Check Flutter
        run: flutter doctor -v
      - name: Checkout gallery code
        uses: actions/checkout@v3
      - run: flutter create .
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    name: Create Windows build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create .
      - run: flutter pub get
      - run: flutter build windows --release -v
      - run: dir -R build\windows\x64\runner\Release
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: .\build\windows\x64\runner\Release\musicplayer.exe

  release:
    name: Release
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branchname
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: apk
      - run: dir -R
      - name: Download EXE from build
        uses: actions/download-artifact@v3
        with:
          name: exe
          path: exe
      - run: dir -R
      - run: mkdir -v upload
      - run: mv apk/app-release.apk upload/app.apk
      - run: mv exe/musicplayer.exe upload/musicplayer.exe
      - name: Upload Programm to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: upload/*
          tag: ${{ steps.branchname.outputs.branch }}/${{ github.run_number }}
          release_name: ${{ github.event.repository.name }} Release v${{ github.run_number }} ${{ steps.branchname.outputs.branch }}
          overwrite: true
          file_glob: true
